# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CleanParen <- function(expr) {
    .Call('_tenpuzzle_CleanParen', PACKAGE = 'tenpuzzle', expr)
}

SolveTenPuzzle <- function(x, tgt) {
    .Call('_tenpuzzle_SolveTenPuzzle', PACKAGE = 'tenpuzzle', x, tgt)
}

test_utils <- function() {
    invisible(.Call('_tenpuzzle_test_utils', PACKAGE = 'tenpuzzle'))
}

test_rational <- function() {
    invisible(.Call('_tenpuzzle_test_rational', PACKAGE = 'tenpuzzle'))
}

test_reduction <- function() {
    invisible(.Call('_tenpuzzle_test_reduction', PACKAGE = 'tenpuzzle'))
}

