# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SolveTenPuzzle <- function(x, tgt, findone, useup, positive) {
    .Call('_tenpuzzle_SolveTenPuzzle', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, positive)
}

SolveTenPuzzleInt <- function(x, tgt, findone, useup, positive) {
    .Call('_tenpuzzle_SolveTenPuzzleInt', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, positive)
}

SolveCountdown <- function(x, tgt, findone, useup, positive) {
    .Call('_tenpuzzle_SolveCountdown', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, positive)
}

SolveCountdownInt <- function(x, tgt, findone, useup, positive) {
    .Call('_tenpuzzle_SolveCountdownInt', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, positive)
}

CleanParen <- function(expr) {
    .Call('_tenpuzzle_CleanParen', PACKAGE = 'tenpuzzle', expr)
}

test_utils <- function() {
    invisible(.Call('_tenpuzzle_test_utils', PACKAGE = 'tenpuzzle'))
}

test_rational <- function() {
    invisible(.Call('_tenpuzzle_test_rational', PACKAGE = 'tenpuzzle'))
}

test_reduction <- function() {
    invisible(.Call('_tenpuzzle_test_reduction', PACKAGE = 'tenpuzzle'))
}

test_hash <- function() {
    invisible(.Call('_tenpuzzle_test_hash', PACKAGE = 'tenpuzzle'))
}

test_withexpr <- function() {
    invisible(.Call('_tenpuzzle_test_withexpr', PACKAGE = 'tenpuzzle'))
}

