# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SolveTenPuzzle <- function(x, tgt, findone, useup, nonnegative, nonzero) {
    .Call('_tenpuzzle_SolveTenPuzzle', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, nonnegative, nonzero)
}

SolveTenPuzzleInt <- function(x, tgt, findone, useup, nonnegative, nonzero) {
    .Call('_tenpuzzle_SolveTenPuzzleInt', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, nonnegative, nonzero)
}

SolveCountdown <- function(x, tgt, findone, useup, nonnegative, nonzero) {
    .Call('_tenpuzzle_SolveCountdown', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, nonnegative, nonzero)
}

SolveCountdownInt <- function(x, tgt, findone, useup, nonnegative, nonzero) {
    .Call('_tenpuzzle_SolveCountdownInt', PACKAGE = 'tenpuzzle', x, tgt, findone, useup, nonnegative, nonzero)
}

CleanParen <- function(expr) {
    .Call('_tenpuzzle_CleanParen', PACKAGE = 'tenpuzzle', expr)
}

#' Convert infix mathematical expression to postfix notation
#'
#' @param x character vector of mathematical expression in the infix notation
#' @return character vector of the postfix notation
#' @examples
#' to_postfix(c("1 + 2 + 3", "(4 - 1)*(-3 + 7) / 5", "(2*3 - 6)*(4 + 1/5)"))
#' @export
to_postfix <- function(x) {
    .Call('_tenpuzzle_to_postfix', PACKAGE = 'tenpuzzle', x)
}

EvaluateExpr <- function(x) {
    .Call('_tenpuzzle_EvaluateExpr', PACKAGE = 'tenpuzzle', x)
}

test_utils <- function() {
    invisible(.Call('_tenpuzzle_test_utils', PACKAGE = 'tenpuzzle'))
}

test_rational <- function() {
    invisible(.Call('_tenpuzzle_test_rational', PACKAGE = 'tenpuzzle'))
}

test_reduction <- function() {
    invisible(.Call('_tenpuzzle_test_reduction', PACKAGE = 'tenpuzzle'))
}

test_hash <- function() {
    invisible(.Call('_tenpuzzle_test_hash', PACKAGE = 'tenpuzzle'))
}

test_withexpr <- function() {
    invisible(.Call('_tenpuzzle_test_withexpr', PACKAGE = 'tenpuzzle'))
}

